#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
export NETWORK_DIR="${ROOT_DIR}/network"
export FABRIC_CFG_PATH="${ROOT_DIR}/network/config"
export CHANNEL_NAME="${CHANNEL_NAME:-farm2forkchannel}"
export FABRIC_VERSION="${FABRIC_VERSION:-3.1.4}"
export ORDERER_NAME="${ORDERER_NAME:-orderer.farm2fork.com}"
export ORDERER_ADMIN_PORT="${ORDERER_ADMIN_PORT:-9443}"
export ORDERER_ADMIN_ADDRESS="${ORDERER_ADMIN_ADDRESS:-localhost:${ORDERER_ADMIN_PORT}}"
export CLI_SERVICE="${CLI_SERVICE:-cli.farm2fork.com}"
export ORGANIZATIONS_DIR="${NETWORK_DIR}/organizations"
export CHANNEL_ARTIFACTS_DIR="${NETWORK_DIR}/channel-artifacts"
export CHANNEL_BLOCK_FILE="${CHANNEL_ARTIFACTS_DIR}/${CHANNEL_NAME}.block"
export COMPOSE_FILE="${NETWORK_DIR}/compose/compose-net.yaml"
export CONTAINER_CHANNEL_BLOCK_FILE="${CONTAINER_CHANNEL_BLOCK_FILE:-/opt/farm2fork/channel-artifacts/${CHANNEL_NAME}.block}"
export CONTAINER_ORDERER_CA="${CONTAINER_ORDERER_CA:-/etc/hyperledger/fabric/ordererOrganizations/farm2fork.com/orderers/${ORDERER_NAME}/tls/ca.crt}"
export CONTAINER_ORDERER_ADMIN_TLS_SIGN_CERT="${CONTAINER_ORDERER_ADMIN_TLS_SIGN_CERT:-/etc/hyperledger/fabric/ordererOrganizations/farm2fork.com/orderers/${ORDERER_NAME}/tls/server.crt}"
export CONTAINER_ORDERER_ADMIN_TLS_PRIVATE_KEY="${CONTAINER_ORDERER_ADMIN_TLS_PRIVATE_KEY:-/etc/hyperledger/fabric/ordererOrganizations/farm2fork.com/orderers/${ORDERER_NAME}/tls/server.key}"
