#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
export NETWORK_DIR="${ROOT_DIR}/network"
export FABRIC_CFG_PATH="${ROOT_DIR}/network/config"
export CHANNEL_NAME="${CHANNEL_NAME:-farm2forkchannel}"
export FABRIC_VERSION="${FABRIC_VERSION:-3.1.4}"
export ORDERER_NAME="${ORDERER_NAME:-orderer.farm2fork.com}"
export ORDERER_ADMIN_PORT="${ORDERER_ADMIN_PORT:-9443}"
export ORDERER_ADMIN_ADDRESS="${ORDERER_ADMIN_ADDRESS:-${ORDERER_NAME}:${ORDERER_ADMIN_PORT}}"
export CLI_SERVICE="${CLI_SERVICE:-cli.farm2fork.com}"
export CHAINCODE_NAME="${CHAINCODE_NAME:-farm2fork-chaincode}"
export CHAINCODE_LANGUAGE="${CHAINCODE_LANGUAGE:-golang}"
export CHAINCODE_VERSION="${CHAINCODE_VERSION:-1.0}"
export CHAINCODE_SEQUENCE="${CHAINCODE_SEQUENCE:-1}"
export CHAINCODE_LABEL="${CHAINCODE_LABEL:-${CHAINCODE_NAME}_1.0}"
export CHAINCODE_DIR="${CHAINCODE_DIR:-${NETWORK_DIR}/chaincode/${CHAINCODE_NAME}}"
export CHAINCODE_PACKAGE_FILE="${CHAINCODE_PACKAGE_FILE:-${NETWORK_DIR}/chaincode/${CHAINCODE_NAME}.tar.gz}"
export CONTAINER_CHAINCODE_DIR="${CONTAINER_CHAINCODE_DIR:-/opt/farm2fork/chaincode/${CHAINCODE_NAME}}"
export CONTAINER_CHAINCODE_PACKAGE_FILE="${CONTAINER_CHAINCODE_PACKAGE_FILE:-/opt/farm2fork/chaincode/${CHAINCODE_NAME}.tar.gz}"
export ORGANIZATIONS_DIR="${NETWORK_DIR}/organizations"
export CHANNEL_ARTIFACTS_DIR="${NETWORK_DIR}/channel-artifacts"
export CHANNEL_BLOCK_FILE="${CHANNEL_ARTIFACTS_DIR}/${CHANNEL_NAME}.block"
export ORDERER_ORGS_DIR="${ORGANIZATIONS_DIR}/ordererOrganizations/farm2fork.com"
export ORDERER_MSP_DIR="${ORDERER_ORGS_DIR}/orderers/${ORDERER_NAME}/msp"
export ORDERER_TLS_DIR="${ORDERER_ORGS_DIR}/orderers/${ORDERER_NAME}/tls"
export ORDERER_ADMIN_TLS_CERT_FILE="${ORGANIZATIONS_DIR}/ordererOrganizations/farm2fork.com/users/Admin@farm2fork.com/tls/client.crt"
export ORDERER_ADMIN_TLS_KEY_FILE="${ORGANIZATIONS_DIR}/ordererOrganizations/farm2fork.com/users/Admin@farm2fork.com/tls/client.key"
export PEER_ORGS_DIR="${ORGANIZATIONS_DIR}/peerOrganizations/farm2fork.com"
export PEER_MSP_DIR="${PEER_ORGS_DIR}/peers/peer0.farm2fork.com/msp"
export PEER_TLS_DIR="${PEER_ORGS_DIR}/peers/peer0.farm2fork.com/tls"
export PEER_ADMIN_MSP_DIR="${ORGANIZATIONS_DIR}/peerOrganizations/farm2fork.com/users/Admin@farm2fork.com/msp"
export COMPOSE_FILE="${NETWORK_DIR}/compose/compose-net.yaml"
export CONTAINER_CHANNEL_BLOCK_FILE="${CONTAINER_CHANNEL_BLOCK_FILE:-/opt/farm2fork/channel-artifacts/${CHANNEL_NAME}.block}"
export CONTAINER_ORDERER_CA="${CONTAINER_ORDERER_CA:-/etc/hyperledger/fabric/ordererOrganizations/farm2fork.com/orderers/${ORDERER_NAME}/tls/ca.crt}"
export CONTAINER_ORDERER_ADMIN_TLS_SIGN_CERT="${CONTAINER_ORDERER_ADMIN_TLS_SIGN_CERT:-/etc/hyperledger/fabric/ordererOrganizations/farm2fork.com/users/Admin@farm2fork.com/tls/client.crt}"
export CONTAINER_ORDERER_ADMIN_TLS_PRIVATE_KEY="${CONTAINER_ORDERER_ADMIN_TLS_PRIVATE_KEY:-/etc/hyperledger/fabric/ordererOrganizations/farm2fork.com/users/Admin@farm2fork.com/tls/client.key}"
