Organizations:
  - &OrdererOrg
    Name: OrdererMSP
    ID: OrdererMSP
    MSPDir: ../organizations/ordererOrganizations/farm2fork.com/msp
  - &Farm2ForkMSP
    Name: Farm2ForkMSP
    ID: Farm2ForkMSP
    MSPDir: ../organizations/peerOrganizations/farm2fork.com/msp
    AnchorPeers:
      - Host: peer0.farm2fork.com
        Port: 7051

Capabilities:
  Channel: &ChannelCapabilities
    V3_0: true
  Orderer: &OrdererCapabilities
    V3_0: true
  Application: &ApplicationCapabilities
    V3_0: true

Profiles:
  Farm2ForkGenesis:
    Orderer:
      OrdererType: etcdraft
      Addresses:
        - orderer.farm2fork.com:7050
      Organizations:
        - *OrdererOrg
      EtcdRaft:
        Consenters:
          - Host: orderer.farm2fork.com
            Port: 7050
            ClientTLSCert: ../organizations/ordererOrganizations/farm2fork.com/orderers/orderer.farm2fork.com/tls/server.crt
            ServerTLSCert: ../organizations/ordererOrganizations/farm2fork.com/orderers/orderer.farm2fork.com/tls/server.crt
      Capabilities: *OrdererCapabilities
    Capabilities: *ChannelCapabilities
  Farm2ForkChannel:
    Consortium: SampleConsortium
    Application:
      Organizations:
        - *Farm2ForkMSP
      Capabilities: *ApplicationCapabilities
